//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 3.4
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// $ANTLR 3.4 C:\\code\\TypeSql\\TypeSql\\Parsing\\RawSqlTransform.g 2013-01-17 17:28:25

// The variable 'variable' is assigned but its value is never used.
#pragma warning disable 219
// Unreachable code detected.
#pragma warning disable 162
// Missing XML comment for publicly visible type or member 'Type_or_Member'
#pragma warning disable 1591
// CLS compliance checking will not be performed on 'type' because it is not visible from outside this assembly.
#pragma warning disable 3019


using System.Collections.Generic;
using TypeSql.Antlr.Runtime;
using TypeSql.Antlr.Runtime.Misc;
using TypeSql.Antlr.Runtime.Tree;
using RewriteRuleITokenStream = TypeSql.Antlr.Runtime.Tree.RewriteRuleTokenStream;

using TypeSql.Antlr3.ST;
using TypeSql.Antlr3.ST.Language;
namespace  TypeSql.Parsing 
{
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "3.4")]
[System.CLSCompliant(false)]
internal partial class RawSqlTransform : Antlr.Runtime.Tree.TreeParser
{
	internal static readonly string[] tokenNames = new string[] {
		"<invalid>", "<EOR>", "<DOWN>", "<UP>", "ANY", "DIGIT", "ID", "INPUT_TOKEN", "NAMESPACE", "NAMESPACE_SEGMENT", "NEWLINE", "OUTPUT_TOKEN", "SQL", "TYPESQL", "USING", "WHITESPACE", "':'", "'@'", "'['", "']'"
	};
	public const int EOF=-1;
	public const int T__16=16;
	public const int T__17=17;
	public const int T__18=18;
	public const int T__19=19;
	public const int ANY=4;
	public const int DIGIT=5;
	public const int ID=6;
	public const int INPUT_TOKEN=7;
	public const int NAMESPACE=8;
	public const int NAMESPACE_SEGMENT=9;
	public const int NEWLINE=10;
	public const int OUTPUT_TOKEN=11;
	public const int SQL=12;
	public const int TYPESQL=13;
	public const int USING=14;
	public const int WHITESPACE=15;

	public RawSqlTransform(ITreeNodeStream input)
		: this(input, new RecognizerSharedState())
	{
	}
	public RawSqlTransform(ITreeNodeStream input, RecognizerSharedState state)
		: base(input, state)
	{
		OnCreated();
	}
	private StringTemplateGroup _templateGroup = new StringTemplateGroup("RawSqlTransformTemplates", typeof(AngleBracketTemplateLexer) );

	public StringTemplateGroup TemplateGroup
	{
		get { return _templateGroup; }
		set { _templateGroup = value; }
	}

	public override string[] TokenNames { get { return RawSqlTransform.tokenNames; } }
	public override string GrammarFileName { get { return "C:\\code\\TypeSql\\TypeSql\\Parsing\\RawSqlTransform.g"; } }


	partial void OnCreated();
	partial void EnterRule(string ruleName, int ruleIndex);
	partial void LeaveRule(string ruleName, int ruleIndex);

	#region Rules
	partial void EnterRule_typeSql();
	partial void LeaveRule_typeSql();

	// $ANTLR start "typeSql"
	// C:\\code\\TypeSql\\TypeSql\\Parsing\\RawSqlTransform.g:14:8: public typeSql : ^( TYPESQL ( usingNamespace )* ^( SQL ( outputToken | inputToken | . )* ) ) ;
	[GrammarRule("typeSql")]
	public TemplateTreeRuleReturnScope<StringTemplate, CommonTree> typeSql()
	{
		EnterRule_typeSql();
		EnterRule("typeSql", 1);
		TraceIn("typeSql", 1);
		TemplateTreeRuleReturnScope<StringTemplate, CommonTree> retval = new TemplateTreeRuleReturnScope<StringTemplate, CommonTree>();
		retval.Start = (CommonTree)input.LT(1);

		try { DebugEnterRule(GrammarFileName, "typeSql");
		DebugLocation(14, 1);
		try
		{
			// C:\\code\\TypeSql\\TypeSql\\Parsing\\RawSqlTransform.g:16:2: ( ^( TYPESQL ( usingNamespace )* ^( SQL ( outputToken | inputToken | . )* ) ) )
			DebugEnterAlt(1);
			// C:\\code\\TypeSql\\TypeSql\\Parsing\\RawSqlTransform.g:16:4: ^( TYPESQL ( usingNamespace )* ^( SQL ( outputToken | inputToken | . )* ) )
			{
			DebugLocation(16, 4);
			DebugLocation(16, 6);
			Match(input,TYPESQL,Follow._TYPESQL_in_typeSql75); 

			Match(input, TokenTypes.Down, null); 
			DebugLocation(17, 4);
			// C:\\code\\TypeSql\\TypeSql\\Parsing\\RawSqlTransform.g:17:4: ( usingNamespace )*
			try { DebugEnterSubRule(1);
			while (true)
			{
				int alt1=2;
				try { DebugEnterDecision(1, false);
				int LA1_0 = input.LA(1);

				if ((LA1_0==USING))
				{
					alt1 = 1;
				}


				} finally { DebugExitDecision(1); }
				switch ( alt1 )
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\code\\TypeSql\\TypeSql\\Parsing\\RawSqlTransform.g:17:4: usingNamespace
					{
					DebugLocation(17, 4);
					PushFollow(Follow._usingNamespace_in_typeSql81);
					usingNamespace();
					PopFollow();


					}
					break;

				default:
					goto loop1;
				}
			}

			loop1:
				;

			} finally { DebugExitSubRule(1); }

			DebugLocation(18, 4);
			DebugLocation(18, 6);
			Match(input,SQL,Follow._SQL_in_typeSql88); 

			if (input.LA(1) == TokenTypes.Down)
			{
				Match(input, TokenTypes.Down, null); 
				DebugLocation(18, 10);
				// C:\\code\\TypeSql\\TypeSql\\Parsing\\RawSqlTransform.g:18:10: ( outputToken | inputToken | . )*
				try { DebugEnterSubRule(2);
				while (true)
				{
					int alt2=4;
					try { DebugEnterDecision(2, false);
					switch (input.LA(1))
					{
					case OUTPUT_TOKEN:
						{
						int LA2_2 = input.LA(2);

						if ((LA2_2==DOWN))
						{
							int LA2_5 = input.LA(3);

							if ((LA2_5==ID))
							{
								int LA2_7 = input.LA(4);

								if ((LA2_7==ID))
								{
									int LA2_9 = input.LA(5);

									if ((LA2_9==UP))
									{
										alt2 = 1;
									}
									else if (((LA2_9>=ANY && LA2_9<=19)))
									{
										alt2 = 3;
									}


								}
								else if (((LA2_7>=UP && LA2_7<=DIGIT)||(LA2_7>=INPUT_TOKEN && LA2_7<=19)))
								{
									alt2 = 3;
								}


							}
							else if (((LA2_5>=ANY && LA2_5<=DIGIT)||(LA2_5>=INPUT_TOKEN && LA2_5<=19)))
							{
								alt2 = 3;
							}


						}
						else if (((LA2_2>=UP && LA2_2<=19)))
						{
							alt2 = 3;
						}


						}
						break;
					case INPUT_TOKEN:
						{
						int LA2_3 = input.LA(2);

						if ((LA2_3==DOWN))
						{
							int LA2_6 = input.LA(3);

							if ((LA2_6==ID))
							{
								int LA2_8 = input.LA(4);

								if ((LA2_8==ID))
								{
									int LA2_10 = input.LA(5);

									if ((LA2_10==UP))
									{
										alt2 = 2;
									}
									else if (((LA2_10>=ANY && LA2_10<=19)))
									{
										alt2 = 3;
									}


								}
								else if (((LA2_8>=UP && LA2_8<=DIGIT)||(LA2_8>=INPUT_TOKEN && LA2_8<=19)))
								{
									alt2 = 3;
								}


							}
							else if (((LA2_6>=ANY && LA2_6<=DIGIT)||(LA2_6>=INPUT_TOKEN && LA2_6<=19)))
							{
								alt2 = 3;
							}


						}
						else if (((LA2_3>=UP && LA2_3<=19)))
						{
							alt2 = 3;
						}


						}
						break;
					case ANY:
					case DIGIT:
					case ID:
					case NAMESPACE:
					case NAMESPACE_SEGMENT:
					case NEWLINE:
					case SQL:
					case TYPESQL:
					case USING:
					case WHITESPACE:
					case 16:
					case 17:
					case 18:
					case 19:
						{
						alt2 = 3;
						}
						break;
					}

					} finally { DebugExitDecision(2); }
					switch ( alt2 )
					{
					case 1:
						DebugEnterAlt(1);
						// C:\\code\\TypeSql\\TypeSql\\Parsing\\RawSqlTransform.g:18:12: outputToken
						{
						DebugLocation(18, 12);
						PushFollow(Follow._outputToken_in_typeSql92);
						outputToken();
						PopFollow();


						}
						break;
					case 2:
						DebugEnterAlt(2);
						// C:\\code\\TypeSql\\TypeSql\\Parsing\\RawSqlTransform.g:18:26: inputToken
						{
						DebugLocation(18, 26);
						PushFollow(Follow._inputToken_in_typeSql96);
						inputToken();
						PopFollow();


						}
						break;
					case 3:
						DebugEnterAlt(3);
						// C:\\code\\TypeSql\\TypeSql\\Parsing\\RawSqlTransform.g:18:39: .
						{
						DebugLocation(18, 39);
						MatchAny(input); 

						}
						break;

					default:
						goto loop2;
					}
				}

				loop2:
					;

				} finally { DebugExitSubRule(2); }


				Match(input, TokenTypes.Up, null); 
			}


			Match(input, TokenTypes.Up, null); 


			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("typeSql", 1);
			LeaveRule("typeSql", 1);
			LeaveRule_typeSql();
		}
		DebugLocation(20, 1);
		} finally { DebugExitRule(GrammarFileName, "typeSql"); }
		return retval;

	}
	// $ANTLR end "typeSql"

	partial void EnterRule_usingNamespace();
	partial void LeaveRule_usingNamespace();

	// $ANTLR start "usingNamespace"
	// C:\\code\\TypeSql\\TypeSql\\Parsing\\RawSqlTransform.g:22:1: usingNamespace : ^( USING NAMESPACE ) -> template( \"\";
	[GrammarRule("usingNamespace")]
	private TemplateTreeRuleReturnScope<StringTemplate, CommonTree> usingNamespace()
	{
		EnterRule_usingNamespace();
		EnterRule("usingNamespace", 2);
		TraceIn("usingNamespace", 2);
		TemplateTreeRuleReturnScope<StringTemplate, CommonTree> retval = new TemplateTreeRuleReturnScope<StringTemplate, CommonTree>();
		retval.Start = (CommonTree)input.LT(1);

		try { DebugEnterRule(GrammarFileName, "usingNamespace");
		DebugLocation(22, 0);
		try
		{
			// C:\\code\\TypeSql\\TypeSql\\Parsing\\RawSqlTransform.g:22:17: ( ^( USING NAMESPACE ) -> template( \"\")
			DebugEnterAlt(1);
			// C:\\code\\TypeSql\\TypeSql\\Parsing\\RawSqlTransform.g:22:19: ^( USING NAMESPACE )
			{
			DebugLocation(22, 19);
			DebugLocation(22, 21);
			Match(input,USING,Follow._USING_in_usingNamespace122); 

			Match(input, TokenTypes.Down, null); 
			DebugLocation(22, 27);
			Match(input,NAMESPACE,Follow._NAMESPACE_in_usingNamespace124); 

			Match(input, TokenTypes.Up, null); 


			// TEMPLATE REWRITE
			// 22:38: -> template( \"\"
			{
				retval.Template = new StringTemplate(TemplateGroup, "");
			}


			((TokenRewriteStream)input.TokenStream).Replace(
				input.TreeAdaptor.GetTokenStartIndex(retval.Start),
				input.TreeAdaptor.GetTokenStopIndex(retval.Start),
				retval.Template);


			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("usingNamespace", 2);
			LeaveRule("usingNamespace", 2);
			LeaveRule_usingNamespace();
		}
		DebugLocation(23, 0);
		} finally { DebugExitRule(GrammarFileName, "usingNamespace"); }
		return retval;

	}
	// $ANTLR end "usingNamespace"

	partial void EnterRule_outputToken();
	partial void LeaveRule_outputToken();

	// $ANTLR start "outputToken"
	// C:\\code\\TypeSql\\TypeSql\\Parsing\\RawSqlTransform.g:25:1: outputToken : ^( OUTPUT_TOKEN id= ID type= ID ) -> template(id=$id.texttype=$type.text) \"[<id>]\";
	[GrammarRule("outputToken")]
	private TemplateTreeRuleReturnScope<StringTemplate, CommonTree> outputToken()
	{
		EnterRule_outputToken();
		EnterRule("outputToken", 3);
		TraceIn("outputToken", 3);
		TemplateTreeRuleReturnScope<StringTemplate, CommonTree> retval = new TemplateTreeRuleReturnScope<StringTemplate, CommonTree>();
		retval.Start = (CommonTree)input.LT(1);

		CommonTree id = default(CommonTree);
		CommonTree type = default(CommonTree);

		try { DebugEnterRule(GrammarFileName, "outputToken");
		DebugLocation(25, 1);
		try
		{
			// C:\\code\\TypeSql\\TypeSql\\Parsing\\RawSqlTransform.g:26:2: ( ^( OUTPUT_TOKEN id= ID type= ID ) -> template(id=$id.texttype=$type.text) \"[<id>]\")
			DebugEnterAlt(1);
			// C:\\code\\TypeSql\\TypeSql\\Parsing\\RawSqlTransform.g:26:4: ^( OUTPUT_TOKEN id= ID type= ID )
			{
			DebugLocation(26, 4);
			DebugLocation(26, 6);
			Match(input,OUTPUT_TOKEN,Follow._OUTPUT_TOKEN_in_outputToken145); 

			Match(input, TokenTypes.Down, null); 
			DebugLocation(26, 21);
			id=(CommonTree)Match(input,ID,Follow._ID_in_outputToken149); 
			DebugLocation(26, 29);
			type=(CommonTree)Match(input,ID,Follow._ID_in_outputToken153); 

			Match(input, TokenTypes.Up, null); 


			// TEMPLATE REWRITE
			// 26:35: -> template(id=$id.texttype=$type.text) \"[<id>]\"
			{
				retval.Template = new StringTemplate(TemplateGroup, "[<id>]",
				new Dictionary<string, object>() { {"id", (id!=null?id.Text:null)}, {"type", (type!=null?type.Text:null)} }
			);
			}


			((TokenRewriteStream)input.TokenStream).Replace(
				input.TreeAdaptor.GetTokenStartIndex(retval.Start),
				input.TreeAdaptor.GetTokenStopIndex(retval.Start),
				retval.Template);


			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("outputToken", 3);
			LeaveRule("outputToken", 3);
			LeaveRule_outputToken();
		}
		DebugLocation(27, 1);
		} finally { DebugExitRule(GrammarFileName, "outputToken"); }
		return retval;

	}
	// $ANTLR end "outputToken"

	partial void EnterRule_inputToken();
	partial void LeaveRule_inputToken();

	// $ANTLR start "inputToken"
	// C:\\code\\TypeSql\\TypeSql\\Parsing\\RawSqlTransform.g:29:1: inputToken : ^( INPUT_TOKEN id= ID type= ID ) -> template(id=$id.texttype=$type.text) \"@<id>\";
	[GrammarRule("inputToken")]
	private TemplateTreeRuleReturnScope<StringTemplate, CommonTree> inputToken()
	{
		EnterRule_inputToken();
		EnterRule("inputToken", 4);
		TraceIn("inputToken", 4);
		TemplateTreeRuleReturnScope<StringTemplate, CommonTree> retval = new TemplateTreeRuleReturnScope<StringTemplate, CommonTree>();
		retval.Start = (CommonTree)input.LT(1);

		CommonTree id = default(CommonTree);
		CommonTree type = default(CommonTree);

		try { DebugEnterRule(GrammarFileName, "inputToken");
		DebugLocation(29, 1);
		try
		{
			// C:\\code\\TypeSql\\TypeSql\\Parsing\\RawSqlTransform.g:30:2: ( ^( INPUT_TOKEN id= ID type= ID ) -> template(id=$id.texttype=$type.text) \"@<id>\")
			DebugEnterAlt(1);
			// C:\\code\\TypeSql\\TypeSql\\Parsing\\RawSqlTransform.g:30:4: ^( INPUT_TOKEN id= ID type= ID )
			{
			DebugLocation(30, 4);
			DebugLocation(30, 6);
			Match(input,INPUT_TOKEN,Follow._INPUT_TOKEN_in_inputToken186); 

			Match(input, TokenTypes.Down, null); 
			DebugLocation(30, 20);
			id=(CommonTree)Match(input,ID,Follow._ID_in_inputToken190); 
			DebugLocation(30, 28);
			type=(CommonTree)Match(input,ID,Follow._ID_in_inputToken194); 

			Match(input, TokenTypes.Up, null); 


			// TEMPLATE REWRITE
			// 30:34: -> template(id=$id.texttype=$type.text) \"@<id>\"
			{
				retval.Template = new StringTemplate(TemplateGroup, "@<id>",
				new Dictionary<string, object>() { {"id", (id!=null?id.Text:null)}, {"type", (type!=null?type.Text:null)} }
			);
			}


			((TokenRewriteStream)input.TokenStream).Replace(
				input.TreeAdaptor.GetTokenStartIndex(retval.Start),
				input.TreeAdaptor.GetTokenStopIndex(retval.Start),
				retval.Template);


			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("inputToken", 4);
			LeaveRule("inputToken", 4);
			LeaveRule_inputToken();
		}
		DebugLocation(31, 1);
		} finally { DebugExitRule(GrammarFileName, "inputToken"); }
		return retval;

	}
	// $ANTLR end "inputToken"
	#endregion Rules


	#region Follow sets
	private static class Follow
	{
		public static readonly BitSet _TYPESQL_in_typeSql75 = new BitSet(new ulong[]{0x4UL});
		public static readonly BitSet _usingNamespace_in_typeSql81 = new BitSet(new ulong[]{0x5000UL});
		public static readonly BitSet _SQL_in_typeSql88 = new BitSet(new ulong[]{0x4UL});
		public static readonly BitSet _outputToken_in_typeSql92 = new BitSet(new ulong[]{0xFFFF8UL});
		public static readonly BitSet _inputToken_in_typeSql96 = new BitSet(new ulong[]{0xFFFF8UL});
		public static readonly BitSet _USING_in_usingNamespace122 = new BitSet(new ulong[]{0x4UL});
		public static readonly BitSet _NAMESPACE_in_usingNamespace124 = new BitSet(new ulong[]{0x8UL});
		public static readonly BitSet _OUTPUT_TOKEN_in_outputToken145 = new BitSet(new ulong[]{0x4UL});
		public static readonly BitSet _ID_in_outputToken149 = new BitSet(new ulong[]{0x40UL});
		public static readonly BitSet _ID_in_outputToken153 = new BitSet(new ulong[]{0x8UL});
		public static readonly BitSet _INPUT_TOKEN_in_inputToken186 = new BitSet(new ulong[]{0x4UL});
		public static readonly BitSet _ID_in_inputToken190 = new BitSet(new ulong[]{0x40UL});
		public static readonly BitSet _ID_in_inputToken194 = new BitSet(new ulong[]{0x8UL});
	}
	#endregion Follow sets
}

} // namespace  TypeSql.Parsing 
